id: ID6EF44D1
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:09:36.043507+00:00
last_modified: 2022-12-14 18:09:36.043513+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-008
  eft-text-version: 1.1.3 2020
  title: Toh_731-Tara_Who_Protects_from_Eight_Dangers-v2
bases:
  '5293':
    source_metadata: null
    order: 1
    base_file: 5293.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
